-- Sakshya — Income Tax reconciliation corpus: export to the app
--
-- The React app is a static site with a CSP that blocks all external egress,
-- and Vite inlines every VITE_* variable into the shipped bundle. So the app
-- can never hold Snowflake credentials or call Snowflake at runtime.
--
-- Instead this file emits two JSON artifacts to paste into src/data/:
--
--   Query A -> src/data/prevalence.json   how often each check fires across
--                                         all 5,000 records. Small.
--   Query B -> src/data/corpus.json       a TaxProfile[] of ~13 real generated
--                                         records, one per check plus clean
--                                         controls. Replaces the hand-typed
--                                         personas in src/data/profiles.ts.
--
-- Run the statements ONE AT A TIME (Ctrl+Enter), not Run All — each JSON
-- artifact is a separate single-cell result you need to save.

USE SCHEMA DB.SCH;

CREATE OR REPLACE FUNCTION ISO_TS(T TIMESTAMP_NTZ)
RETURNS VARCHAR
AS $$ TO_VARCHAR(T, 'YYYY-MM-DD') || 'T' || TO_VARCHAR(T, 'HH24:MI:SS') || '+05:30' $$;

CREATE OR REPLACE FUNCTION ISO_DATE(D DATE)
RETURNS VARCHAR
AS $$ TO_VARCHAR(D, 'YYYY-MM-DD') $$;


-- ===========================================================================
-- Query A — prevalence.json
-- ===========================================================================
SELECT TO_JSON(OBJECT_CONSTRUCT(
    'corpusSize', (SELECT COUNT(*) FROM TAXPAYER),
    'note', 'Prevalence within a synthetic corpus generated by snowflake/02_seed.sql. '
         || 'It is a property of that generator, not a measurement of Indian taxpayers. '
         || 'Only the e-verification rate is grounded in published filing figures.',
    'checks', (
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
            'checkCode', CHECK_CODE,
            'severity', SEVERITY,
            'taxpayersAffected', TAXPAYERS_AFFECTED,
            'percentOfCorpus', PERCENT_OF_CORPUS
        )) WITHIN GROUP (ORDER BY TAXPAYERS_AFFECTED DESC)
        FROM V_PREVALENCE
    )
)) AS PREVALENCE_JSON;


-- ===========================================================================
-- Query B — corpus.json
-- ===========================================================================

-- One representative per check (lowest id that fires it), plus two clean records.
CREATE OR REPLACE VIEW V_SAMPLE_TAXPAYER AS
SELECT MIN(TAXPAYER_ID) AS TAXPAYER_ID FROM V_FINDING GROUP BY CHECK_CODE
UNION
SELECT TAXPAYER_ID FROM (
    SELECT t.TAXPAYER_ID
    FROM TAXPAYER t
    LEFT JOIN V_FINDING f ON f.TAXPAYER_ID = t.TAXPAYER_ID
    WHERE f.TAXPAYER_ID IS NULL
    ORDER BY t.TAXPAYER_ID
    LIMIT 2
);

-- Every child collection is pre-aggregated into its own CTE and joined once.
-- Snowflake rejects correlated aggregate subqueries inside a SELECT list
-- ("Unsupported subquery type cannot be evaluated"), so none are used here.
-- 'sample' is a reserved word, hence 'picked'.
WITH picked AS (
    SELECT t.*
    FROM TAXPAYER t
    JOIN V_SAMPLE_TAXPAYER s ON s.TAXPAYER_ID = t.TAXPAYER_ID
),

-- The evidence ledger. Bank statements and rent receipts are deliberately
-- absent, so a notice naming more than two documents leaves a real gap.
docs AS (
    SELECT p.TAXPAYER_ID, 1 AS SORT_KEY, OBJECT_CONSTRUCT(
        'id', 'doc-form16', 'kind', 'form-16', 'label', 'Form 16 Part A',
        'reference', f.TAN,
        'capturedAt', ISO_TS('2026-06-15 10:00:00'::TIMESTAMP_NTZ),
        'note', 'Employer statement of salary and tax deducted.') AS DOC
    FROM picked p JOIN FORM16 f ON f.TAXPAYER_ID = p.TAXPAYER_ID

    UNION ALL
    SELECT p.TAXPAYER_ID, 2, OBJECT_CONSTRUCT(
        'id', 'doc-26as', 'kind', 'form-26as', 'label', 'Form 26AS',
        'reference', p.PAN_MASKED || ' / ' || p.ASSESSMENT_YEAR,
        'capturedAt', ISO_TS('2026-07-10 09:30:00'::TIMESTAMP_NTZ),
        'note', 'Departmental statement of tax credits.')
    FROM picked p

    UNION ALL
    SELECT p.TAXPAYER_ID, 3, OBJECT_CONSTRUCT(
        'id', 'doc-ais', 'kind', 'ais', 'label', 'Annual Information Statement',
        'reference', p.PAN_MASKED || ' / AIS',
        'capturedAt', ISO_TS('2026-07-12 09:30:00'::TIMESTAMP_NTZ),
        'note', 'Reported financial transactions for the year.')
    FROM picked p

    UNION ALL
    SELECT p.TAXPAYER_ID, 4, OBJECT_CONSTRUCT(
        'id', 'doc-return', 'kind', 'return', 'label', p.ITR_FORM || ' as submitted',
        'reference', p.ITR_FORM || ' / ' || p.ASSESSMENT_YEAR,
        'capturedAt', ISO_TS(COALESCE(p.FILED_ON, p.DUE_DATE)),
        'note', 'The return the taxpayer submitted.')
    FROM picked p

    UNION ALL
    SELECT p.TAXPAYER_ID, 5, OBJECT_CONSTRUCT(
        'id', 'doc-challan-' || c.CHALLAN_ID, 'kind', 'challan',
        'label', CASE WHEN c.KIND = 'advance-tax' THEN 'Advance tax challan'
                      ELSE 'Self-assessment tax challan' END,
        'reference', c.CIN,
        'capturedAt', ISO_TS(c.PAID_AT),
        'note', 'Bank receipt for tax paid.')
    FROM picked p JOIN CHALLAN c ON c.TAXPAYER_ID = p.TAXPAYER_ID

    UNION ALL
    SELECT p.TAXPAYER_ID, 6, OBJECT_CONSTRUCT(
        'id', 'doc-notice', 'kind', 'notice', 'label', 'Notice ' || n.CODE,
        'reference', n.CODE || ' / ' || ISO_DATE(n.ISSUED_ON),
        'capturedAt', ISO_TS(n.ISSUED_ON::TIMESTAMP_NTZ),
        'note', 'Notice received on the e-filing portal.')
    FROM picked p JOIN NOTICE n ON n.TAXPAYER_ID = p.TAXPAYER_ID
),

docs_agg AS (
    SELECT TAXPAYER_ID,
           ARRAY_AGG(DOC) WITHIN GROUP (ORDER BY SORT_KEY, DOC:id) AS DOCUMENTS
    FROM docs GROUP BY TAXPAYER_ID
),

challan_agg AS (
    SELECT c.TAXPAYER_ID, ARRAY_AGG(OBJECT_CONSTRUCT(
        'documentId', 'doc-challan-' || c.CHALLAN_ID,
        'kind', c.KIND, 'cin', c.CIN,
        'amountPaise', c.AMOUNT_PAISE, 'paidAt', ISO_TS(c.PAID_AT)))
        WITHIN GROUP (ORDER BY c.CHALLAN_ID) AS CHALLANS
    FROM CHALLAN c JOIN picked p ON p.TAXPAYER_ID = c.TAXPAYER_ID
    GROUP BY c.TAXPAYER_ID
),

credit_agg AS (
    SELECT tc.TAXPAYER_ID, ARRAY_AGG(OBJECT_CONSTRUCT(
        'cin', tc.CIN, 'amountPaise', tc.AMOUNT_PAISE))
        WITHIN GROUP (ORDER BY tc.CIN) AS CREDITS
    FROM TAX_CREDIT tc JOIN picked p ON p.TAXPAYER_ID = tc.TAXPAYER_ID
    GROUP BY tc.TAXPAYER_ID
),

ais_agg AS (
    SELECT a.TAXPAYER_ID, ARRAY_AGG(OBJECT_CONSTRUCT(
        'id', 'ais-' || a.ENTRY_ID, 'payer', a.PAYER,
        'amountPaise', a.AMOUNT_PAISE, 'reportedOn', ISO_DATE(a.REPORTED_ON)))
        WITHIN GROUP (ORDER BY a.ENTRY_ID) AS ENTRIES
    FROM AIS_INTEREST a JOIN picked p ON p.TAXPAYER_ID = a.TAXPAYER_ID
    GROUP BY a.TAXPAYER_ID
),

special_agg AS (
    SELECT sr.TAXPAYER_ID, ARRAY_AGG(OBJECT_CONSTRUCT(
        'section', sr.SECTION,
        'label', CASE sr.SECTION
            WHEN '111A' THEN 'Short-term capital gains (111A)'
            WHEN '112A' THEN 'Long-term capital gains (112A)'
            WHEN '112'  THEN 'Long-term capital gains (112)'
            ELSE             'Virtual digital assets (115BBH)' END,
        'amountPaise', sr.AMOUNT_PAISE))
        WITHIN GROUP (ORDER BY sr.SECTION) AS ITEMS
    FROM SPECIAL_RATE_INCOME sr JOIN picked p ON p.TAXPAYER_ID = sr.TAXPAYER_ID
    GROUP BY sr.TAXPAYER_ID
),

notice_obj AS (
    SELECT n.TAXPAYER_ID, OBJECT_CONSTRUCT(
        'documentId', 'doc-notice', 'code', n.CODE,
        'title', CASE WHEN n.CODE = '139(9)' THEN 'Defective return notice'
                      ELSE 'Intimation under section 143(1)' END,
        'respondBy', ISO_DATE(n.RESPOND_BY),
        -- Only doc-form16 and doc-26as exist in the ledger above.
        'requiredDocumentIds', ARRAY_SLICE(ARRAY_CONSTRUCT(
            'doc-form16', 'doc-26as', 'doc-bank-statement', 'doc-rent-receipt'),
            0, n.DOCS_REQUIRED)) AS NOTICE
    FROM NOTICE n JOIN picked p ON p.TAXPAYER_ID = n.TAXPAYER_ID
)

SELECT TO_JSON(ARRAY_AGG(PROFILE) WITHIN GROUP (ORDER BY TAXPAYER_ID)) AS CORPUS_JSON
FROM (
    SELECT p.TAXPAYER_ID, OBJECT_CONSTRUCT_KEEP_NULL(
        'id', 'record-' || LPAD(TO_VARCHAR(p.TAXPAYER_ID), 4, '0'),
        'personaLabel', 'Record ' || p.PAN_MASKED,
        'situation', p.ITR_FORM || ', ' || p.REGIME || ' regime, total income '
                     || RUPEES(p.TOTAL_INCOME_PAISE) || '. Drawn from a generated corpus.',
        'assessmentYear', p.ASSESSMENT_YEAR,
        'documents', dg.DOCUMENTS,

        'dueDate', ISO_TS(p.DUE_DATE),
        'filedOn', ISO_TS(p.FILED_ON),
        'everifiedOn', ISO_TS(p.EVERIFIED_ON),

        'challans', COALESCE(ch.CHALLANS, ARRAY_CONSTRUCT()),
        'taxCredits', COALESCE(cr.CREDITS, ARRAY_CONSTRUCT()),

        'form16TdsPaise', f.TDS_PAISE,
        'form26asTdsPaise', a.TDS_PAISE,
        'claimedTdsPaise', r.CLAIMED_TDS_PAISE,

        'aisInterest', COALESCE(ai.ENTRIES, ARRAY_CONSTRUCT()),
        'declaredInterestPaise', r.DECLARED_INTEREST_PAISE,

        'npsClaimPercent', r.NPS_CLAIM_PERCENT,
        'form16NpsCapPercent', f.NPS_CAP_PERCENT,

        'rebateClaimedPaise', r.REBATE_CLAIMED_PAISE,
        'specialRateIncome', COALESCE(sp.ITEMS, ARRAY_CONSTRUCT()),

        'refundClaimedPaise', p.REFUND_CLAIMED_PAISE,
        'notice', nt.NOTICE
    ) AS PROFILE
    FROM picked p
    JOIN FORM16       f  ON f.TAXPAYER_ID  = p.TAXPAYER_ID
    JOIN FORM26AS     a  ON a.TAXPAYER_ID  = p.TAXPAYER_ID
    JOIN RETURN_CLAIM r  ON r.TAXPAYER_ID  = p.TAXPAYER_ID
    LEFT JOIN docs_agg    dg ON dg.TAXPAYER_ID = p.TAXPAYER_ID
    LEFT JOIN challan_agg ch ON ch.TAXPAYER_ID = p.TAXPAYER_ID
    LEFT JOIN credit_agg  cr ON cr.TAXPAYER_ID = p.TAXPAYER_ID
    LEFT JOIN ais_agg     ai ON ai.TAXPAYER_ID = p.TAXPAYER_ID
    LEFT JOIN special_agg sp ON sp.TAXPAYER_ID = p.TAXPAYER_ID
    LEFT JOIN notice_obj  nt ON nt.TAXPAYER_ID = p.TAXPAYER_ID
);


-- ---------------------------------------------------------------------------
-- Verify the export before pasting it anywhere
-- ---------------------------------------------------------------------------

-- Which records were picked, and what each one demonstrates.
SELECT s.TAXPAYER_ID,
       COALESCE(LISTAGG(f.CHECK_CODE, ', ') WITHIN GROUP (ORDER BY f.CHECK_CODE), '(clean)') AS FIRES
FROM V_SAMPLE_TAXPAYER s
LEFT JOIN V_FINDING f ON f.TAXPAYER_ID = s.TAXPAYER_ID
GROUP BY s.TAXPAYER_ID ORDER BY s.TAXPAYER_ID;

-- Every check must appear at least once, or the app loses a case.
SELECT p.CHECK_CODE
FROM V_PREVALENCE p
WHERE p.CHECK_CODE NOT IN (
    SELECT f.CHECK_CODE FROM V_FINDING f
    JOIN V_SAMPLE_TAXPAYER s ON s.TAXPAYER_ID = f.TAXPAYER_ID);
