-- Sakshya — Income Tax reconciliation corpus: analysis
--
-- Run order: 01_schema -> 02_seed -> 03_checks -> 05_analytics (04_export is
-- independent and only needed when refreshing the app's JSON artifacts).
--
-- Everything here reads FINDING_FLAT, the materialised table 03_checks.sql
-- builds. Re-deriving V_FINDING for each query would rescan the corpus eleven
-- times over.
--
-- ===========================================================================
-- WHAT THESE NUMBERS ARE, AND ARE NOT
-- ===========================================================================
-- This corpus is generated by 02_seed.sql. Every defect cohort is a modulus of
-- TAXPAYER_ID. So a rate here is a property of that generator and nothing else.
--
-- It is NOT a measurement of Indian taxpayers. It cannot be, at any corpus
-- size: 15 crore invented records are still invented. Scale buys realistic
-- query behaviour, not evidence. Do not screenshot a percentage from this file
-- and present it as a fact about India.
--
-- The one relationship in the data that is real is the one the generator was
-- built to contain: filers in the challan-sync cohort both pay late and go
-- uncredited. Section 5 finds it. That is a rediscovery of a decision made in
-- the seed, not a discovery about the world.

USE SCHEMA DB.SCH;


-- ===========================================================================
-- 1. Corpus profile
-- ===========================================================================

-- Row counts and on-disk size straight from metadata, so this costs nothing
-- and needs no warehouse time even at 15 crore.
SELECT TABLE_NAME,
       ROW_COUNT,
       ROUND(BYTES / POWER(1024, 3), 2) AS GIB
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SCH' AND TABLE_TYPE = 'BASE TABLE'
ORDER BY ROW_COUNT DESC;

-- Shape of the corpus. APPROX_COUNT_DISTINCT uses HyperLogLog: within about
-- 1.6% of the true count, and it does not have to hold 15 crore keys in memory
-- the way COUNT(DISTINCT) does.
SELECT COUNT(*)                              AS TAXPAYERS,
       APPROX_COUNT_DISTINCT(PAN_MASKED)     AS DISTINCT_MASKED_PANS,
       COUNT_IF(REGIME = 'new')              AS NEW_REGIME,
       COUNT_IF(FILED_ON > DUE_DATE)         AS FILED_AFTER_DUE_DATE,
       COUNT_IF(EVERIFIED_ON IS NULL)        AS NEVER_EVERIFIED,
       ROUND(AVG(TOTAL_INCOME_PAISE) / 100)  AS MEAN_INCOME_RUPEES,
       ROUND(APPROX_PERCENTILE(TOTAL_INCOME_PAISE, 0.5) / 100) AS MEDIAN_INCOME_RUPEES
FROM TAXPAYER;


-- ===========================================================================
-- 2. How findings stack up per taxpayer
-- ===========================================================================

-- A taxpayer with six findings has a different problem from six taxpayers with
-- one each. The distribution says which corpus this is.
WITH per_taxpayer AS (
    SELECT t.TAXPAYER_ID, COUNT(f.CHECK_CODE) AS FINDINGS
    FROM TAXPAYER t
    LEFT JOIN FINDING_FLAT f ON f.TAXPAYER_ID = t.TAXPAYER_ID
    GROUP BY t.TAXPAYER_ID
)
SELECT FINDINGS,
       COUNT(*) AS TAXPAYERS,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PERCENT_OF_CORPUS,
       ROUND(100.0 * SUM(COUNT(*)) OVER (ORDER BY FINDINGS)
             / SUM(COUNT(*)) OVER (), 2) AS CUMULATIVE_PERCENT
FROM per_taxpayer
GROUP BY FINDINGS
ORDER BY FINDINGS;


-- ===========================================================================
-- 3. Which checks fire together
-- ===========================================================================
--
-- Lift is how much more often two checks co-occur than they would if they were
-- independent. Lift of 1.0 means the pair carries no information. Above 1.0
-- means one finding raises the odds of the other, and those pairs are the ones
-- worth showing a taxpayer together rather than as two separate lines.
--
-- CHECK_B > CHECK_A gives each unordered pair once and drops self-pairs, which
-- halves the join without a DISTINCT afterwards.
WITH n AS (
    SELECT TOTAL FROM CORPUS_SUMMARY
),
pairs AS (
    SELECT a.CHECK_CODE AS CHECK_A,
           b.CHECK_CODE AS CHECK_B,
           COUNT(*)     AS BOTH
    FROM FINDING_FLAT a
    JOIN FINDING_FLAT b
      ON b.TAXPAYER_ID = a.TAXPAYER_ID
     AND b.CHECK_CODE  > a.CHECK_CODE
    GROUP BY 1, 2
)
SELECT p.CHECK_A,
       p.CHECK_B,
       p.BOTH                                             AS TAXPAYERS_WITH_BOTH,
       pa.TAXPAYERS_AFFECTED                              AS ONLY_A_TOTAL,
       pb.TAXPAYERS_AFFECTED                              AS ONLY_B_TOTAL,
       ROUND(100.0 * p.BOTH / n.TOTAL, 3)                 AS PERCENT_OF_CORPUS,
       ROUND((p.BOTH / n.TOTAL)
             / ((pa.TAXPAYERS_AFFECTED / n.TOTAL)
              * (pb.TAXPAYERS_AFFECTED / n.TOTAL)), 2)    AS LIFT
FROM pairs p
CROSS JOIN n
JOIN PREVALENCE_SUMMARY pa ON pa.CHECK_CODE = p.CHECK_A
JOIN PREVALENCE_SUMMARY pb ON pb.CHECK_CODE = p.CHECK_B
ORDER BY LIFT DESC, TAXPAYERS_WITH_BOTH DESC;


-- ===========================================================================
-- 4. Finding rate across the income range
-- ===========================================================================
--
-- WIDTH_BUCKET, not NTILE. NTILE has to sort the whole table through a single
-- ordered window to know which decile a row lands in; at 15 crore that spills
-- to disk. The seed's income range is known (₹3L to ₹25L), so the bucket is
-- arithmetic and each row is placed independently.
WITH banded AS (
    SELECT TAXPAYER_ID,
           WIDTH_BUCKET(TOTAL_INCOME_PAISE, 300000 * 100, 2500000 * 100, 10) AS BAND
    FROM TAXPAYER
)
SELECT b.BAND,
       '₹' || TO_VARCHAR(3 + (b.BAND - 1) * 2.2, '99.9') || 'L to ₹'
            || TO_VARCHAR(3 + b.BAND * 2.2, '99.9') || 'L' AS INCOME_RANGE,
       COUNT(DISTINCT b.TAXPAYER_ID)                       AS TAXPAYERS,
       COUNT(f.CHECK_CODE)                                 AS FINDINGS,
       ROUND(COUNT(f.CHECK_CODE)
             / COUNT(DISTINCT b.TAXPAYER_ID), 3)           AS FINDINGS_PER_TAXPAYER
FROM banded b
LEFT JOIN FINDING_FLAT f ON f.TAXPAYER_ID = b.TAXPAYER_ID
GROUP BY b.BAND
ORDER BY b.BAND;


-- ===========================================================================
-- 5. Filing time against the challan-credit gap
-- ===========================================================================
--
-- The one relationship the generator deliberately contains. Returns submitted
-- after the due date are the same cohort whose challans never reached the
-- taxes-paid schedule, so the two columns move together by construction.
--
-- Read this as a demonstration that the query finds a known planted signal,
-- which is the only way to trust it would find an unknown one. It is not
-- evidence that late filing causes anything, here or anywhere.
SELECT CASE
           WHEN t.FILED_ON > t.DUE_DATE                             THEN '3. after the due date'
           WHEN t.FILED_ON > DATEADD(hour, -48, t.DUE_DATE)         THEN '2. final 48 hours'
           ELSE                                                          '1. earlier'
       END AS SUBMISSION_WINDOW,
       COUNT(DISTINCT t.TAXPAYER_ID)                                AS TAXPAYERS,
       COUNT(DISTINCT CASE WHEN f.CHECK_CODE = 'challan-credit'
                           THEN t.TAXPAYER_ID END)                  AS UNCREDITED_CHALLAN,
       ROUND(100.0 * COUNT(DISTINCT CASE WHEN f.CHECK_CODE = 'challan-credit'
                                         THEN t.TAXPAYER_ID END)
             / COUNT(DISTINCT t.TAXPAYER_ID), 2)                    AS PERCENT
FROM TAXPAYER t
LEFT JOIN FINDING_FLAT f ON f.TAXPAYER_ID = t.TAXPAYER_ID
WHERE t.FILED_ON IS NOT NULL
GROUP BY 1
ORDER BY 1;


-- ===========================================================================
-- 6. Rupee gap behind each finding
-- ===========================================================================
--
-- Prevalence counts people. This counts money, which is a different ranking:
-- a rare check over large sums can matter more than a common one over small.
-- Only the four checks with a well-defined two-record difference appear. The
-- rest (a missing verification date, a duplicated entry) have no single amount
-- that would be honest to report.
WITH gaps AS (
    SELECT 'tds-match' AS CHECK_CODE, ABS(f.TDS_PAISE - a.TDS_PAISE) AS GAP_PAISE
    FROM FORM16 f JOIN FORM26AS a ON a.TAXPAYER_ID = f.TAXPAYER_ID
    WHERE f.TDS_PAISE <> a.TDS_PAISE

    UNION ALL
    SELECT 'claimed-tds', ABS(r.CLAIMED_TDS_PAISE - a.TDS_PAISE)
    FROM RETURN_CLAIM r JOIN FORM26AS a ON a.TAXPAYER_ID = r.TAXPAYER_ID
    WHERE r.CLAIMED_TDS_PAISE <> a.TDS_PAISE

    UNION ALL
    SELECT 'challan-credit', c.AMOUNT_PAISE
    FROM CHALLAN c
    LEFT JOIN TAX_CREDIT t ON t.TAXPAYER_ID = c.TAXPAYER_ID AND t.CIN = c.CIN
    WHERE t.CIN IS NULL

    UNION ALL
    SELECT 'interest-declared', ABS(r.DECLARED_INTEREST_PAISE - d.DISTINCT_TOTAL)
    FROM RETURN_CLAIM r
    JOIN (
        SELECT TAXPAYER_ID, SUM(AMOUNT_PAISE) AS DISTINCT_TOTAL
        FROM (SELECT DISTINCT TAXPAYER_ID, PAYER, AMOUNT_PAISE, REPORTED_ON FROM AIS_INTEREST)
        GROUP BY TAXPAYER_ID
    ) d ON d.TAXPAYER_ID = r.TAXPAYER_ID
    WHERE r.DECLARED_INTEREST_PAISE <> d.DISTINCT_TOTAL
)
SELECT CHECK_CODE,
       COUNT(*)                                                  AS RECORDS,
       ROUND(SUM(GAP_PAISE) / 10000000 / 100, 2)                 AS TOTAL_GAP_CRORE,
       ROUND(AVG(GAP_PAISE) / 100)                               AS MEAN_GAP_RUPEES,
       ROUND(APPROX_PERCENTILE(GAP_PAISE, 0.5)  / 100)           AS MEDIAN_GAP_RUPEES,
       ROUND(APPROX_PERCENTILE(GAP_PAISE, 0.99) / 100)           AS P99_GAP_RUPEES
FROM gaps
GROUP BY CHECK_CODE
ORDER BY TOTAL_GAP_CRORE DESC;


-- ===========================================================================
-- 7. Working on a sample
-- ===========================================================================
--
-- While drafting a new check, run it against a sample first. SAMPLE reads only
-- the micro-partitions it needs, so this is a rounding error against the cost
-- of a full pass, and the shape of the answer is the same.
SELECT CHECK_CODE, COUNT(*) AS AFFECTED_IN_SAMPLE
FROM FINDING_FLAT SAMPLE (100000 ROWS)
GROUP BY CHECK_CODE
ORDER BY AFFECTED_IN_SAMPLE DESC;


-- ===========================================================================
-- 8. Cortex AI over the findings
-- ===========================================================================
--
-- Run 8.0 first. It turns Cortex on and reports which of the three functions
-- used below this account actually has.
--
-- The prompts are written to hold the AI to the same rule the rest of the
-- product follows: state the difference between two named records, and stop.
-- No legal or tax conclusion, no prediction about a refund or a notice, no
-- claim about why the portal did anything. An LLM will happily produce all
-- three unless it is told not to, which is why the constraint is in the prompt
-- and not left to the model's judgement.


-- ---------------------------------------------------------------------------
-- 8.0 Enable Cortex, then find out what you have
-- ---------------------------------------------------------------------------

-- Account-level parameters, so this needs ACCOUNTADMIN.
USE ROLE ACCOUNTADMIN;

-- Look before changing anything. If CORTEX_ENABLED_CROSS_REGION already reads
-- ANY_REGION, the ALTERs below are no-ops.
SELECT CURRENT_REGION() AS REGION, CURRENT_ACCOUNT() AS ACCOUNT;
SHOW PARAMETERS LIKE 'CORTEX%' IN ACCOUNT;

-- Cortex models are hosted in a handful of regions. If the account is not in
-- one of them, every call fails on availability rather than syntax, which is
-- what makes it look like the function does not exist.
--
-- Read before running: cross-region inference sends the PROMPT TEXT to a
-- Snowflake-managed region outside your own. That is fine here, because every
-- record in this corpus is invented. Against real taxpayer data it would be a
-- governance decision, not a convenience one.
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- To keep inference inside one boundary, name a region group instead:
-- 'AWS_US', 'AWS_EU', 'AWS_APJ', 'AZURE_US'. 'DISABLED' is the way back.

-- Probe each function separately. They are not one feature. COMPLETE has been
-- generally available far longer than AI_CLASSIFY and AI_AGG, so an account can
-- pass 8a and still fail 8b and 8c.
--
-- If these three return text, Cortex works and there is nothing left to do.
-- Skip the rest of 8.0.
SELECT SNOWFLAKE.CORTEX.COMPLETE('llama3.1-8b', 'Reply with the word OK') AS COMPLETE_WORKS;
SELECT AI_CLASSIFY('a bank statement', ['document', 'person']) AS CLASSIFY_WORKS;
SELECT AI_AGG(C, 'Reply with the word OK') AS AGG_WORKS FROM (SELECT 'x' AS C);

-- llama3.1-8b is the smallest and most widely deployed model, so it is the
-- honest test of whether Cortex works at all. If it succeeds where
-- mistral-large2 fails, the limit is that one model's regional availability
-- and swapping the model name in 8a is the whole fix.


-- ---------------------------------------------------------------------------
-- 8.0b Only if a probe above failed
-- ---------------------------------------------------------------------------
--
-- Neither statement here is part of enabling Cortex, and both commonly error.
-- The errors are usually benign, and say something worth reading:
--
--   "invalid parameter 'CORTEX_MODELS_ALLOWLIST'"
--       This account has no model allowlist, so there is no restriction to
--       lift. Nothing to do.
--
--   "Database role 'SNOWFLAKE.CORTEX_USER' does not exist or not authorized"
--       Either Cortex is not provisioned on this account at all, or the role
--       is already reachable through PUBLIC, which ACCOUNTADMIN inherits. The
--       query below separates those two, which the error text does not.

-- Does the role exist? Absent means Cortex is not provisioned here, and no
-- grant will conjure it. Present means the grant was simply redundant.
SHOW DATABASE ROLES IN DATABASE SNOWFLAKE;

-- Run only if a probe failed with a privilege error AND CORTEX_USER is listed
-- above. Replace ACCOUNTADMIN with the role that hit the error.
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN;

-- Run only if a probe failed naming a model that is not permitted.
ALTER ACCOUNT SET CORTEX_MODELS_ALLOWLIST = 'All';


-- 8a. Turn one taxpayer's findings into a plain-language paragraph.
WITH one AS (
    SELECT f.TAXPAYER_ID,
           LISTAGG(v.HEADLINE || ' — ' || v.DETAIL, '\n') AS FINDINGS
    FROM FINDING_FLAT f
    JOIN V_FINDING v ON v.TAXPAYER_ID = f.TAXPAYER_ID AND v.CHECK_CODE = f.CHECK_CODE
    WHERE f.TAXPAYER_ID = 25
    GROUP BY f.TAXPAYER_ID
)
SELECT TAXPAYER_ID,
       SNOWFLAKE.CORTEX.COMPLETE('mistral-large2',
           'Rewrite the following findings as one short paragraph a person with '
        || 'no tax training can read. Rules you must follow: describe only the '
        || 'difference between the named records. Do not say what the tax '
        || 'outcome will be. Do not predict a refund, a penalty or a notice. Do '
        || 'not guess why any of it happened. Do not give advice. Use simple '
        || 'Indian English. Findings:\n' || FINDINGS) AS PLAIN_LANGUAGE
FROM one;

-- 8b. Group the checks by the kind of record mismatch they describe.
-- AI_CLASSIFY picks from the labels given, so the output stays a closed set
-- rather than free text that would need parsing.
SELECT CHECK_CODE,
       TAXPAYERS_AFFECTED,
       AI_CLASSIFY(CHECK_CODE,
           ['amount mismatch', 'missing record', 'timing', 'duplicate entry'])
           :labels[0]::VARCHAR AS MISMATCH_KIND
FROM PREVALENCE_SUMMARY
ORDER BY TAXPAYERS_AFFECTED DESC;

-- 8c. Summarise across many rows at once.
-- AI_AGG is the aggregate form: it reduces a whole column to one answer instead
-- of calling a model per row, which at 15 crore rows would be neither
-- affordable nor finishable. Sampled again on top of that, because the summary
-- of a representative slice is the same summary.
SELECT AI_AGG(HEADLINE,
           'These are checks run against invented test records, not real people. '
        || 'List the distinct kinds of record disagreement described here. '
        || 'Do not estimate how common anything is in the real world.') AS THEMES
FROM (SELECT DISTINCT HEADLINE FROM V_FINDING SAMPLE (10000 ROWS));
